<a href="https://colab.research.google.com/github/ppojawa/neural-network-course/blob/master/02_basics/02_activation_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* @author: krakowiakpawel9@gmail.com  
* @site: e-smartdata.org

### Spis treści:
1. [Funkcje aktywacji](#a0)
    1. [Import bibliotek](#a1)
    2. [ReLU Function - Rectified Linear Unit](#a2)
    3. [Funkcja Sigmoid](#a3)
    4. [Tanh Function](#a4)
    5. [Funkcja Softmax](#a5)
  

### <a name='a0'></a> 1. Funkcje Aktywacji
#### <a name='a1'></a> 1.1 Import bibliotek

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import plotly.express as px
import math

np.set_printoptions(precision=6)

#### <a name='a2'></a> 1.2 ReLU Function - Rectified Linear Unit
####     $$f(x) = max(x, 0)$$


In [2]:
def max_relu(x):
    return max(x, 0.0)

In [3]:
for i in [-10., -5., 0., 5., 10.]:
    print(max_relu(i))

0.0
0.0
0.0
5.0
10.0


In [4]:
data = np.random.randn(50)
data = sorted(data)
data

[-1.5616034018295541,
 -1.095495766621287,
 -1.0773219191092152,
 -0.8990082441267916,
 -0.8431156498935098,
 -0.6840404458925134,
 -0.6535005726324299,
 -0.5882925050814042,
 -0.519040356383759,
 -0.5161609497508989,
 -0.48778180796945037,
 -0.4785648401030574,
 -0.47080430208657986,
 -0.47019357623353,
 -0.45355374575629814,
 -0.43671772332246006,
 -0.417165492404933,
 -0.4107788611297925,
 -0.4085777952755302,
 -0.22476459485894373,
 -0.1402520172951781,
 -0.07341871350010765,
 -0.027819806182697415,
 -0.019069953585536415,
 0.05048150563464804,
 0.13657350920241731,
 0.17105156659810086,
 0.19200308145049813,
 0.23387344880102437,
 0.25832019583825994,
 0.5091973344197562,
 0.5111615019474003,
 0.5114486192353151,
 0.6424291239702489,
 0.7540438402076288,
 0.7674526806102446,
 0.8491608401136232,
 0.8529405946345394,
 0.8555194122744344,
 0.8575929813211316,
 0.864923370436976,
 0.9706606442204865,
 1.1437998257710134,
 1.2450411614188022,
 1.3598319819299485,
 1.5203624073398847,


In [5]:
# wygenerowanie danych do wykresu
max_relu_data = np.array([max_relu(x) for x in data])
max_relu_data

array([0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.050482, 0.136574, 0.171052, 0.192003, 0.233873, 0.25832 ,
       0.509197, 0.511162, 0.511449, 0.642429, 0.754044, 0.767453,
       0.849161, 0.852941, 0.855519, 0.857593, 0.864923, 0.970661,
       1.1438  , 1.245041, 1.359832, 1.520362, 1.527476, 1.538899,
       1.650601, 1.670071])

In [6]:
df = pd.DataFrame({'data': data, 'max_relu_data': max_relu_data})
df.head()

data  max_relu_data
0 -1.561603            0.0
1 -1.095496            0.0
2 -1.077322            0.0
3 -0.899008            0.0
4 -0.843116            0.0

In [7]:
px.line(df, x='data', y='max_relu_data', width=700, height=400, title='ReLU Function')

#### <a name='a3'></a> 1.3 Funkcja Sigmoid
####    $$f(x) = \frac{1}{1 + e^{-x}}$$

In [8]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [9]:
for i in [-5., -3., -1., 0., 1., 3., 5.]:
    print(sigmoid(i))

0.0066928509242848554
0.04742587317756678
0.2689414213699951
0.5
0.7310585786300049
0.9525741268224334
0.9933071490757153


In [10]:
data = 3 * np.random.randn(50)
data = sorted(data)
data

[-6.9725850916618635,
 -5.14171450891871,
 -4.731851293012324,
 -4.17796534265789,
 -3.881625487659635,
 -3.0453541472686716,
 -2.7996964577359043,
 -2.5324784872682606,
 -2.0407555209752024,
 -1.7780437173172006,
 -1.6432061350893377,
 -1.2461050390269521,
 -1.2135024486031034,
 -0.9532385369427165,
 -0.7130148978315631,
 -0.4860368437284748,
 -0.3274180326576195,
 -0.2987908558560202,
 -0.11633772812609813,
 0.04627678928302916,
 0.10998728588307706,
 0.12372084276855239,
 0.3689648864546227,
 0.45630760710649365,
 0.5409429259626389,
 0.5461296630063766,
 0.5850097039635207,
 0.6000073338168299,
 0.7105902162937716,
 0.7807576300270929,
 0.8294306600966972,
 1.2062952604213562,
 1.4001365742084821,
 1.5853112327108527,
 1.6910591983313714,
 1.7536239235713964,
 2.313389433867266,
 2.4637634866287983,
 2.5377019049737206,
 2.6599243642654056,
 3.6152164373825606,
 3.7216418527316977,
 3.9325333210945828,
 3.9786496279240557,
 4.262314614809182,
 4.711579794263079,
 4.8071601923776,
 

In [11]:
sigmoid_data = [sigmoid(x) for x in sorted(data)]
sigmoid_data

[0.000936349382069973,
 0.005813658983107132,
 0.00873320496288062,
 0.015098215862030317,
 0.020200799158175825,
 0.04541847252281113,
 0.05734058095480426,
 0.07361245077079306,
 0.1149898224511221,
 0.14454486349551154,
 0.16202927522160238,
 0.22337510337198477,
 0.2290819197972285,
 0.2782339926578855,
 0.3289330005549389,
 0.3808276293869943,
 0.4188689878846943,
 0.42585309509689323,
 0.470948327155137,
 0.5115671331033986,
 0.5274691354099499,
 0.5308908173231378,
 0.5912088348481503,
 0.6121378732320409,
 0.6320317390713663,
 0.6332371779568255,
 0.6422193226757709,
 0.6456579840857162,
 0.6705315629153918,
 0.6858433775800289,
 0.6962345324388393,
 0.7696427817365773,
 0.8022055599284328,
 0.8299554033711115,
 0.8443634039788039,
 0.8524093018980516,
 0.9099798919099953,
 0.9215621397988428,
 0.926742960808229,
 0.9346200449732893,
 0.9737941288020815,
 0.9763773202345076,
 0.98078257390154,
 0.981632778101556,
 0.9861061075957305,
 0.9910895468738423,
 0.9918951936860161,
 0

In [12]:
df = pd.DataFrame({'data': data, 'sigmoid_data': sigmoid_data})
df.head()

data  sigmoid_data
0 -6.972585      0.000936
1 -5.141715      0.005814
2 -4.731851      0.008733
3 -4.177965      0.015098
4 -3.881625      0.020201

In [13]:
px.line(df, x='data', y='sigmoid_data', width=700, height=400, title='Sigmoid Function')

#### <a name='a4'></a> 1.4 Tanh Function

####   $$tanh (x) = \frac{e^{x} - e^{-x}}{e^{x} + e^{-x}}$$

In [14]:
def tanh(x):
    return (np.exp(x) - np.exp(-x)) / (np.exp(x) + np.exp(-x))

In [15]:
data = 2 * np.random.randn(100)
data = sorted(data)
data

[-5.040882388587023,
 -4.815439571355001,
 -4.242763605578934,
 -4.094797446527339,
 -4.059952780044475,
 -3.929132731034156,
 -3.682343355382407,
 -3.5083812624915547,
 -3.1596292334593623,
 -2.8708189915995743,
 -2.69617823101769,
 -2.6635948758927497,
 -2.521776926159335,
 -2.242153889702811,
 -2.202693827606739,
 -2.165649595692957,
 -2.1204313001147854,
 -2.0461999908595216,
 -2.0459056355157887,
 -1.9408293624569206,
 -1.7784056873821739,
 -1.775325066002466,
 -1.7724901197395726,
 -1.7697057645933523,
 -1.766374284503568,
 -1.6652616511139118,
 -1.6622670144951337,
 -1.6531347936369312,
 -1.5359650391444164,
 -1.3947611580720598,
 -1.2767850853720608,
 -1.2508150515358138,
 -1.2140516256002178,
 -1.0488886501543662,
 -0.8175291205198516,
 -0.6790952268138502,
 -0.6706932950111946,
 -0.6693031575694375,
 -0.6474733804357465,
 -0.601118079752186,
 -0.5850225591378099,
 -0.5133304966745268,
 -0.39726589743361146,
 -0.3467243032348897,
 -0.3281983963794566,
 -0.2869592421324093,
 -0

In [16]:
tanh_data = [tanh(x) for x in sorted(data)]
tanh_data

[-0.9999163324568165,
 -0.9998686700408328,
 -0.999587216140178,
 -0.999445101420347,
 -0.9994050635066783,
 -0.9992272111865997,
 -0.9987343539219683,
 -0.9982081589471078,
 -0.9964039201044355,
 -0.993601522259885,
 -0.9909387680540217,
 -0.9903315619979431,
 -0.9871811269492963,
 -0.9776824540942535,
 -0.9758718938815517,
 -0.9740404765844467,
 -0.9716182220762173,
 -0.9671503441983197,
 -0.9671313174775986,
 -0.9595997173744557,
 -0.9445234268352467,
 -0.9441901345428341,
 -0.9438817039688377,
 -0.9435771665347773,
 -0.9432106786274179,
 -0.930922447843701,
 -0.9305218975950084,
 -0.9292865385532271,
 -0.9114398479049647,
 -0.8842139933544582,
 -0.8556259921195188,
 -0.8485120345634214,
 -0.8378907321704703,
 -0.781373912771922,
 -0.673722778677371,
 -0.5909308832304415,
 -0.5854357463698503,
 -0.5845213140934402,
 -0.5699666056476965,
 -0.5378446899122798,
 -0.5263063419408707,
 -0.4725360957219642,
 -0.37760713114994526,
 -0.33346729367350353,
 -0.31690102811444615,
 -0.279333704

In [17]:
df = pd.DataFrame({'data': data, 'tanh_data': tanh_data})
df.head()

data  tanh_data
0 -5.040882  -0.999916
1 -4.815440  -0.999869
2 -4.242764  -0.999587
3 -4.094797  -0.999445
4 -4.059953  -0.999405

In [18]:
px.line(df, x='data', y='tanh_data', width=700, height=400, title='Tanh Function')

#### <a name='a5'></a> 1.5 Softmax Function

####   $$S(x_i)=\frac{e^{x_{i}}}{\sum_{j=1}^{N}e^{x_j}},\ \ dla\ i = 1,...,N$$

####   $$S(x_1)=\frac{e^{x_{1}}}{\sum_{j=1}^{N}e^{x_j}}$$

In [19]:
def softmax(x):
    e_x = np.exp(x)
    denominator = np.sum(e_x, axis=1)
    denominator = denominator[:, np.newaxis]
    return e_x / denominator

In [20]:
data = np.random.randn(4, 5)
data

array([[-1.056215,  0.976281,  0.962398,  1.093181,  1.241709],
       [ 0.552668, -1.132608, -0.396501,  0.972047,  1.037128],
       [ 0.136129,  0.438996, -0.56858 , -1.224651, -0.05811 ],
       [ 0.12131 ,  1.293611,  1.816237,  0.088296,  2.547017]])

In [21]:
result = softmax(data)
result

array([[0.028823, 0.220011, 0.216978, 0.247294, 0.286893],
       [0.21201 , 0.039305, 0.082061, 0.32247 , 0.344155],
       [0.254588, 0.344645, 0.125831, 0.065292, 0.209644],
       [0.045551, 0.147103, 0.248082, 0.044072, 0.515192]])

In [22]:
result.sum(axis=1)

array([1., 1., 1., 1.])